pipeline:
  name: pranay-cicd-test
  identifier: pranaycicdtest
  projectIdentifier: Security_Test_Scans
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: test-stage
        identifier: teststage
        description: ""
        type: CI
        spec:
          cloneCodebase: false
          caching:
            enabled: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: account.harnessciplatformng2
              namespace: harness-delegate-prod
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    connectorRef: pranaypersonal
                    image: pranaycshah/todolist-demo:alpine-slim
                    shell: Bash
                    command: |-
                      PR="This is a script for Unit test"
                      echo $PR
                      echo "Unit tests are done"

                      <+trigger.prTitle>
        variables:
          - name: gcp_key
            type: Secret
            description: ""
            required: false
            value: dummy_secret
          - name: gcp_key2
            type: Secret
            description: ""
            required: false
            value: dummy_secret
