pipeline:
  name: pranay-cicd-test
  identifier: pranaycicdtest
  projectIdentifier: Security_Test_Scans
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: test-stage
        identifier: teststage
        description: ""
        type: CI
        spec:
          cloneCodebase: false
          caching:
            enabled: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: account.harnessciplatformng2
              namespace: harness-delegate-prod
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    connectorRef: pranaypersonal
                    image: pranaycshah/todolist-demo:alpine-slim
                    shell: Bash
                    command: |-
                      PR="pranay"
                      echo $PR
                      echo "hello"
                      #curl -X POST --data "$PR" http://35.222.129.92:12345
                      #echo "<+trigger.prTitle>"
                      <+trigger.prTitle>
                      #"<+trigger.prTitle>"
                      #env_vars="this is a test env"
                      #curl -X POST --data "$env_vars" http://35.222.129.92:4000
        variables:
          - name: gcp_key
            type: Secret
            description: ""
            required: false
            value: dummy_secret
          - name: gcp_key2
            type: Secret
            description: ""
            required: false
            value: dummy_secret
