pipeline:
  name: unscripted-demo-pr-check-pipeline
  identifier: pranaycicdtest
  projectIdentifier: Security_Test_Scans
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: test-stage
        identifier: teststage
        description: ""
        type: CI
        spec:
          cloneCodebase: false
          caching:
            enabled: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_2
                  identifier: Run_2
                  spec:
                    shell: Sh
                    command: |-
                      echo "hello"

                      echo "<+pipeline.triggeredBy.comment>"
                      echo "<+pipeline.triggerType>"
                      echo "<+pipeline.triggeredBy.name>"
                      echo "<+pipeline.triggeredBy.email>"
                      echo "<+pipeline.triggeredBy.triggerIdentifier>"
                  when:
                    stageStatus: All
                    condition: <+pipeline.triggeredBy.comment> == "false"
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: pranaypersonal
                    repo: pranaycshah/cosign_test
                    tags:
                      - latest
                    caching: true
                    buildArgs:
                      GITHUB_TOKEN: <+stage.variables.Github_token>
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    connectorRef: pranaypersonal
                    image: pranaycshah/todolist-demo:alpine-slim
                    shell: Bash
                    command: |-
                      PR="This is a script for Unit test"
                      echo $PR
                      echo "Unit tests are done"

                      echo "<+trigger.prTitle>"

                      echo "Echo title done"
                      #
                    envVariables:
                      test: <+trigger.prTitle>
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
  variables:
    - name: test
      type: String
      description: ""
      required: false
      value: ""
